Northwind/src/views/about_view.py
from flask import Blueprint, render_template

# Managing the entire view
about_blueprint = Blueprint("about_view", __name__) # "about_view" is the name of the view


@about_blueprint.route("/about") # Route
def about(): # View Function
    return render_template("about.html", active = "about")

Northwind/src/views/auth_view.py
from flask import Blueprint, render_template, redirect, url_for, request
from facades.auth_facade import AuthFacade
from models.client_errors import ValidationError, AuthError

# Managing the entire view
auth_blueprint = Blueprint("auth_view", __name__)

# Create auth facade: 
auth_facade = AuthFacade()

# Register new user:
@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():
    try:
        if request.method == "GET": return render_template("register.html", user = {})
        auth_facade.register()
        return redirect(url_for("home_view.home"))
    except ValidationError as err:
        return render_template("register.html", error = err.message, user = err.model)


# Login existing user:
@auth_blueprint.route("/login", methods=["GET", "POST"])
def login():
    try:
        if request.method == "GET": 
            err = request.args.get("error") # Take error from url (if exists)
            return render_template("login.html", error = err, credentials = {})
        auth_facade.login()
        return redirect(url_for("home_view.home"))
    except (ValidationError, AuthError) as err:
        return render_template("login.html", error = err.message, credentials = err.model)

# Logout user:
@auth_blueprint.route("/logout")
def logout():
    auth_facade.logout()
    return redirect(url_for("home_view.home"))

Northwind/src/views/home_view.py
from flask import Blueprint, render_template

# Managing the entire view
home_blueprint = Blueprint("home_view", __name__) # "home_view" is the name of the view


@home_blueprint.route("/") # Route
@home_blueprint.route("/home") # Route
def home(): # View Function
    return render_template("home.html", active = "home")


Northwind/src/views/products_view.py
from flask import Blueprint, render_template, send_file, redirect, url_for, request
from facades.products_facade import ProductsFacade
from facades.auth_facade import AuthFacade
from utils.image_handler import ImageHandler
from models.client_errors import ResourceNotFoundError, ValidationError, AuthError

# Managing the entire view
products_blueprint = Blueprint("products_view", __name__) # "products_view" is the name of the view

# Create facade: 
products_facade = ProductsFacade()
auth_facade = AuthFacade()

# Display all products
@products_blueprint.route("/products") # Route
def list(): # View Function
    all_products = products_facade.get_all_products()
    return render_template("products.html", products = all_products, active = "list")

# Display single product:
@products_blueprint.route("/products/details/<int:id>") # <int:id> is called a route parameter
def details(id):
    try:
        one_product = products_facade.get_one_product(id)
        return render_template("details.html", product = one_product)
    except ResourceNotFoundError as err:
        return render_template("404.html", error = err.message)

# Return image file:
@products_blueprint.route("/products/images/<string:image_name>")
def get_image(image_name):
    # image_name --> 01a5a6d5-6cc4-4e72-8f5d-e44efd3bc3d7.jpg
    # image_path --> C:\7732-11\2024-01-12\Northwind\src\static\images\products\01a5a6d5-6cc4-4e72-8f5d-e44efd3bc3d7.jpg
    image_path = ImageHandler.get_image_path(image_name)
    return send_file(image_path) # Returns a complete file (an image file with pixels of the image...)

# Adding new product:
@products_blueprint.route("/products/new", methods=["GET", "POST"])
def insert():
    try:
        auth_facade.block_anonymous()
        if request.method == "GET": return render_template("insert.html", active = "insert")
        products_facade.add_product()
        return redirect(url_for("products_view.list"))
    except AuthError as err: 
        return redirect(url_for("auth_view.login", error = err.message)) # Send error to url query string
    except ValidationError as err:
        return render_template("insert.html", error = err.message)


# Updating existing product:
@products_blueprint.route("/products/edit/<int:id>", methods=["GET", "POST"])
def edit(id):
    try:
        auth_facade.block_anonymous()
        if request.method == "GET": 
            one_product = products_facade.get_one_product(id)
            return render_template("edit.html", product = one_product)
        products_facade.update_product()
        return redirect(url_for("products_view.list"))
    except AuthError as err: 
        return redirect(url_for("auth_view.login", error = err.message)) # Send error to url query string
    except ResourceNotFoundError as err:
        return render_template("404.html", error = err.message) 
    except ValidationError as err:
        return render_template("edit.html", error = err.message, product = err.model)

# Delete existing product:
@products_blueprint.route("/products/delete/<int:id>")
def delete(id):
    try:
        auth_facade.block_non_admin()
        products_facade.delete_product(id)
        return redirect(url_for("products_view.list"))
    except AuthError as err: 
        return redirect(url_for("auth_view.login", error = err.message)) # Send error to url query string

Northwind/src/templates/about.html
{% extends "layout.html" %}

{% block title %}Northwind | About{% endblock title %}

{% block content %}
<h2>About Page</h2>
{% endblock content %}

Northwind/src/templates/auth.html
<div>

    {% if user %}

        <span>Hello {{user["first_name"]}} {{user["last_name"]}}</span>
        <span> | </span>
        <a href="{{ url_for('auth_view.logout') }}">Logout</a>

    {% else %}

        <span>Hello Guest</span>
        <span> | </span>
        <a href="{{ url_for('auth_view.login') }}">Login</a>
        <span> | </span>
        <a href="{{ url_for('auth_view.register') }}">Register</a>

    {% endif %}

</div>

Northwind/src/templates/details.html
{% extends "layout.html" %}

{% block title %}Product Details{% endblock title %}

{% block content %}

<h5>Name: {{ product.name }}</h5>
<h5>Price: {{ product.price }}</h5>
<h5>Stock: {{ product.stock }}</h5>

<img src="{{ url_for('products_view.get_image', image_name = (product.image_name if product.image_name else '---') ) }}">
<br><br>

<a href="{{ url_for('products_view.list') }}">Back</a>
<span> | </span>
<a href="{{ url_for('products_view.edit', id = product.id) }}">Edit</a>
<span> | </span>
<a onclick="confirmDelete()" href="{{ url_for('products_view.delete', id = product.id) }}">Delete</a>


{% endblock content %}

Northwind/src/templates/edit.html
{% extends "layout.html" %}

{% block title %}Edit Product{% endblock title %}

{% block content %}

<form method="post" class="fancy-form" enctype="multipart/form-data">

    <input type="hidden" name="id" value="{{product.id}}">

    <label>Name: </label>
    <input type="text" name="name" class="form-control" value="{{product.name}}" required minlength="2" maxlength="100">

    <label>Price: </label>
    <input type="number" name="price" step="0.01" class="form-control" value="{{product.price}}" required min="0" max="1000">

    <label>Stock: </label>
    <input type="number" name="stock" class="form-control" value="{{product.stock}}" required min="0" max="1000">

    <label>Image: </label>
    <input type="file" name="image" class="form-control" accept="image/*">

    <button class="btn btn-primary w-100">Update</button>
    
</form>

{% endblock content %}

Northwind/src/templates/home.html
{% extends "layout.html" %}

{% block title %}Northwind | Home{% endblock title %}

{% block content %}

<h2>Welcome to Northwind Website!</h2>

<img src="{{ url_for('static', filename='images/logo.jpg') }}">

{% endblock content %}

Northwind/src/templates/insert.html
{% extends "layout.html" %}

{% block title %}Add Product{% endblock title %}

{% block content %}

<form method="post" class="fancy-form" enctype="multipart/form-data">

    <label>Name: </label>
    <input type="text" name="name" class="form-control" required minlength="2" maxlength="100">

    <label>Price: </label>
    <input type="number" name="price" step="0.01" class="form-control" required min="0" max="1000">

    <label>Stock: </label>
    <input type="number" name="stock" class="form-control" required min="0" max="1000">

    <label>Image: </label>
    <input type="file" name="image" accept="image/*" class="form-control" required>

    <button class="btn btn-primary w-100">Add</button>
    
</form>

{% endblock content %}

Northwind/src/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <script defer src="{{ url_for('static', filename='js/main.js')}}"></script>
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>

    <!-- Get the user from the session for later use: -->
    {% set user = session.get("current_user") %}

    <div class="layout">

        <header>
            {% include "nav.html" %}
        </header>

        <aside>
        
            <a href="{{ url_for('home_view.home') }}" {% if active=='home' %} class="active" {% endif %}>Home</a>
            <a href="{{ url_for('products_view.list') }}" {% if active=='list' %} class="active" {% endif %}>Products</a>

            {% if admin %}
                <a href="{{ url_for('products_view.insert') }}" {% if active=='insert' %} class="active" {% endif %}>Add Product</a>
            {% endif %}

            <a href="{{ url_for('about_view.about') }}" {% if active=='about' %} class="active" {% endif %}>About</a>

        </aside>

        <main>
            <!-- Place holder for a block named "content" specified in the pages: -->
            {% block content %}
            {% endblock content %}

            {% if error %} <span class="error">{{error}}</span> {% endif %}

        </main>

        <footer>
            <div>All Rights Reserved ©</div>
        </footer>

    </div>

</body>

</html>

Northwind/src/templates/login.html
{% extends "layout.html" %}

{% block title %}Login{% endblock title %}

{% block content %}

<form method="post" class="fancy-form">

    <label>Email: </label>
    <input type="email" name="email" value="{{credentials.email}}" class="form-control" required minlength="5" maxlength="100">

    <label>Password: </label>
    <input type="password" name="password" value="{{credentials.password}}" class="form-control" required minlength="4" maxlength="100">

    <button class="btn btn-primary w-100">Login</button>
    
</form>

{% endblock content %}

Northwind/src/templates/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">

      <a class="navbar-brand" href="#">Northwind</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
          </li>
        </ul>

        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

        <div class="auth btn">
            {% include "auth.html" %}
        </div>

      </div>
    </div>
  </nav>

Northwind/src/templates/products.html
{% extends "layout.html" %}

{% block title %}Northwind | Products{% endblock title %}

{% block content %}

<table class="table table-bordered table-striped table-hover products-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Stock</th>
            <th>Image</th>
        </tr>
    </thead>
    <tbody>
        <!-- Templating Engine -->
        {% for p in products %}
            <tr>
                <td>
                    <a href="{{ url_for('products_view.details', id = p.id ) }}">{{ p.name }}</a>
                </td>
                <td>${{ p.price | round(2) }}</td>
                <td>{{ p.stock }}</td>
                <td>
                    <img src="{{ url_for('products_view.get_image', image_name = (p.image_name if p.image_name else '---')) }}">
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock content %}

Northwind/src/templates/register.html
{% extends "layout.html" %}

{% block title %}Register{% endblock title %}

{% block content %}

<form method="post" class="fancy-form">

    <label>First name: </label>
    <input type="text" name="first_name" value="{{user.first_name}}" class="form-control" required minlength="2" maxlength="20">

    <label>Last name: </label>
    <input type="text" name="last_name" value="{{user.last_name}}" class="form-control" required minlength="2" maxlength="30">

    <label>Email: </label>
    <input type="email" name="email" value="{{user.email}}" class="form-control" required minlength="5" maxlength="100">

    <label>Password: </label>
    <input type="password" name="password" value="{{user.password}}" class="form-control" required minlength="4" maxlength="100">

    <button class="btn btn-primary w-100">Register</button>
    
</form>

{% endblock content %}